# Generated by Django 4.1.5 on 2023-01-26 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.DecimalField(decimal_places=0, max_digits=5)),
                ('content_id', models.DecimalField(decimal_places=0, max_digits=5)),
                ('article', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_name', models.CharField(max_length=200)),
                ('site_url', models.CharField(max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('site_strategy', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usrename', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('bookshelf', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_url', models.CharField(default='', max_length=200)),
                ('coverUrl', models.CharField(default='', max_length=200)),
                ('durChaptertitle', models.CharField(default='', max_length=200)),
                ('durChapterindex', models.DecimalField(decimal_places=0, default=1, max_digits=5)),
                ('durChapterTime', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('latestChaptertitle', models.CharField(default='', max_length=200)),
                ('latestChaptertindex', models.DecimalField(decimal_places=0, default=1, max_digits=5)),
                ('latestChapterTime', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('source', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='api.site')),
            ],
        ),
    ]
