# Generated by Django 4.1.5 on 2023-01-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.DecimalField(decimal_places=0, max_digits=5)),
                ('data', models.JSONField()),
            ],
        ),
    ]
