# Generated by Django 4.1.5 on 2023-01-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book_coverurl_book_durchaptertime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
