# Generated by Django 4.1.5 on 2023-01-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bookcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
