# Generated by Django 4.1.5 on 2023-01-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_book_book_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='durChapterTime',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14),
        ),
    ]
