# Generated by Django 4.1.5 on 2023-01-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_book_durchaptertime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='latestChapterTime',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14),
        ),
    ]
