# Generated by Django 4.1.5 on 2023-01-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_book_latestchaptertime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.DecimalField(decimal_places=0, max_digits=5)),
                ('content_id', models.DecimalField(decimal_places=0, max_digits=5)),
                ('article', models.TextField()),
            ],
        ),
    ]
